language: node_js
node_js:
  - "stable"
sudo: true
dist: trusty

branches:
  only:
  - master
  - feature/travis-ci

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - npm install

script:
  - npm run lint
  - ng test --watch false
  - npm run e2e
